Repository comoser/baby-food-intro-api, pull requests merged in 2022-10, with the labels that each got.

#19 feat(profile): add profile update for parent
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  src/auth/auth.service.ts
  src/parents/dtos/update/update-parent-profile.request.dto.ts
  src/parents/factories/parent-entity.factory.ts
  src/parents/integrations/parent-integration.service.ts
  src/parents/parent.entity.ts
  src/parents/parents.controller.ts
  src/parents/parents.service.ts
Labels: hacktoberfest, hacktoberfest-accepted

#20 docs(postman): add postman collection info to the readme
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#24 feat(all-contributors): add all contributors configuration
  .all-contributorsrc
  README.md
Labels: hacktoberfest-accepted

#35 chore(husky): add husky and conventional commits as standard
  .github/pull_request_template.md
  .husky/commit-msg
  commitlint.config.js
  package.json
  yarn.lock
Labels: hacktoberfest, hacktoberfest-accepted

#37 feat(food-introduction): add update food introduction feature
  src/auth/auth.service.ts
  src/babies/babies.service.ts
  src/babies/factories/create-baby-entity.factory.ts
  src/babies/factories/share-baby-invitation-entity.factory.ts
  src/babies/factories/update-baby-entity.factory.ts
  src/babies/share-baby-invitation.entity.builder.ts
  src/food-introductions/dtos/update/update-food-introduction.request.dto.ts
  src/food-introductions/dtos/update/update-food-introduction.response.dto.ts
  src/food-introductions/factories/create-food-introduction-entity.factory.ts
  src/food-introductions/factories/food-introduction-entity.factory.ts
  src/food-introductions/factories/update-food-introduction-entity.factory.ts
  src/food-introductions/food-introduction.entity.builder.ts
  src/food-introductions/food-introductions.controller.ts
  src/food-introductions/food-introductions.service.ts
  src/parents/factories/create-parent-entity.factory.ts
  src/parents/factories/parent-entity.factory.ts
  src/parents/factories/update-parent-entity.factory.ts
  src/parents/parent.entity.builder.ts
  src/parents/parents.service.ts
Labels: hacktoberfest

#39 feat(cicd): add pr title validation
  .github/workflows/pr-title-checker.yaml
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, feature

#41 feat(cicd): add label checker validation
  .github/workflows/label-checker.yaml
Labels: hacktoberfest, hacktoberfest-accepted, feature

#43 feat(cicd): add release drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yaml
Labels: hacktoberfest, hacktoberfest-accepted, feature

#45 feat(cicd): update changelog
  .github/workflows/update-changelog.yaml
  CHANGELOG.md
Labels: hacktoberfest, hacktoberfest-accepted, feature

#48 fix(cicd): workflow runner name
  .github/workflows/label-checker.yaml
  .github/workflows/pr-title-checker.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/update-changelog.yaml
Labels: bug, hacktoberfest, patch
